### ISSUE TITLE
Custom org page: Admin - topline numbers

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-ckan#2718]
- [ ] Dataset ID - do we need it? In case we don't it should be removed. For custom location we don't have it - ping @cjhendrix 
- [ ] Create a different section for topline numbers (similar with custom location page)
  In the end we should have the following sections:
- General information
- Custom styles
  - logos
  - Background logo same...
  - Custom Styling
- Topline numbers
  - Resource ID
- Visualization Configuration

**Comment by cjhendrix** [comment]
Regarding item 1, yes, I've been saying we should remove it, but apparently it was needed for some reason.  Happy to see it go.   What might be nice, however, is for the user to be able to see the dataset name (linked to the dataset) and resource name once a resource id has been entered.

**Comment by danmihaila** [comment]
I agree with you @cjhendrix. But this features should come also with a refactoring of the admin interface once we decide this is top priority
pinging @amcguire62

**Comment by cjhendrix** [comment]
@danmihaila Totally agree on prioritization comment you made above.

**Comment by aalecs** [comment]
The dataset field is still being used throughout the controller and needs to be removed consistently - topline numbers not working after original fix.

**Comment by danmihaila** [comment]
Can you check why custom location doesn't need it?

**Comment by mbellotti** [comment]
@danmihalia It's just the way @alexandru-m-g wrote this part of the controller. My bad, I didn't notice it until now, but it's an easy thing to fix. Testing it now, will push in five minutes.

**Comment by mbellotti** [comment]
Ready to go as soon as Arti merges my PR :)

**Comment by danmihaila** [comment]
@aalecs  to confirm, but I think the PR is a mixed of Sprint 55 issues and Sprint 56 issues. I am not sure if they should be deployed to PROD as hotfix.

**Comment by mbellotti** [comment]
Yeah, I didn't notice that the original PR (with a 55 issue) hadn't been merged until after I pushed the Sprint 56 issues. I've been spoiled by your fast turn around Dan :) I gave into my inherent sloppiness

**Comment by alexandru-m-g** [comment]
The controller needed both because initially we used both dataset id and resource name to identify the datastore. If we're getting rid of the datastore id from the form than it needs to be removed from the  controller as well, shouldn't be too complicated.

**Comment by aalecs** [comment]
@danmihaila - I changed this issue to Sprint 56 will be merged into dev
Hope we'll better test our fixes next time :)

**Comment by aalecs** [comment]
@mbellotti 
Before merging into dev I took a look a quick look at the commit and because I investigated the issue (while it was happening on production this morning) I knew a bit about the fix and seen you missed this:

``` python
    def _get_top_line_src_info(self, json_dict):
        if 'topline_dataset' in json_dict and 'topline_resource' in json_dict:
            return (json_dict['topline_dataset'], json_dict['topline_resource'])
        return (None, None)
```

Then I thought to myself that you probably tested and it's working even with this bit of code in it, but then I tested it on your branch and it's **still not working**.

Also in your commit I don't see the html changes(removing the field). These were reverted on prod and on dev.

**Comment by mbellotti** [comment]
.... which is why the commit message said it was ready for testing on staging. I don't have the topline data for wfp on my local environment and since this issue seemed to have some urgency to it I figured we would prefer to use the servers we bought for testing to do the testing, rather than wait for me to extract an up-to-date sql dump from staging and redo my local db. I tested it to make sure saving or loading a custom org didn't create 500 errors.

**Comment by aalecs** [comment]
@mbellotti - we're not in a hurry ... please test your fix before commiting ... we're not using the staging server to test our fixes, the overhead to redeploy is big enough and sometimes the server is used for demo purposes.

**Comment by mbellotti** [comment]
![screen shot 2015-06-02 at 10 05 12 pm](https://cloud.githubusercontent.com/assets/489152/7951260/7cb3a95e-0973-11e5-8595-d79c4ad8a55b.png)

It works

**Comment by danmihaila** [comment]
I see that we added an extra section at the beginning.
We should keep Basic Details and remove General information. I checked old mockups and prod and we have only Basic Details. I'm not sure why we added General information.
See screenshot attached
![screen shot 2015-06-04 at 12 09 17](https://cloud.githubusercontent.com/assets/3865844/7980804/322a5a04-0ab3-11e5-9172-c6e512381a4d.png)

**Comment by danmihaila** [comment]
this appears when going to "/organization/new"

**Comment by mbellotti** [comment]
Oooo good catch. We did not add anything new, what happens is that the Basic Information header is in another template that is only used by the new page. Easy fix.
